/* Generated by MyraPad at 5/4/2024 9:48:33 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace MUDMapBuilder.Sample.UI
{
	partial class MainForm: Panel
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "Reset";

			_buttonReset = new Button();
			_buttonReset.Id = "_buttonReset";
			_buttonReset.Content = label1;

			var label2 = new Label();
			label2.Text = "Step";

			_buttonStep = new Button();
			_buttonStep.Id = "_buttonStep";
			_buttonStep.Content = label2;

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.Widgets.Add(_buttonReset);
			horizontalStackPanel1.Widgets.Add(_buttonStep);

			_panelMap = new ScrollViewer();
			_panelMap.Id = "_panelMap";
			StackPanel.SetProportionType(_panelMap, Myra.Graphics2D.UI.ProportionType.Fill);

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 8;
			verticalStackPanel1.Widgets.Add(horizontalStackPanel1);
			verticalStackPanel1.Widgets.Add(_panelMap);

			
			Widgets.Add(verticalStackPanel1);
		}

		
		public Button _buttonReset;
		public Button _buttonStep;
		public ScrollViewer _panelMap;
	}
}
