/* Generated by MyraPad at 5/5/2024 4:29:52 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace MUDMapBuilder.Sample.UI
{
	partial class MainForm: Panel
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "<<";

			_buttonStart = new Button();
			_buttonStart.Id = "_buttonStart";
			_buttonStart.Content = label1;

			_spinButtonStep = new SpinButton();
			_spinButtonStep.Width = 50;
			_spinButtonStep.Id = "_spinButtonStep";

			var label2 = new Label();
			label2.Text = ">>";

			_buttonEnd = new Button();
			_buttonEnd.Id = "_buttonEnd";
			_buttonEnd.Content = label2;

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.Widgets.Add(_buttonStart);
			horizontalStackPanel1.Widgets.Add(_spinButtonStep);
			horizontalStackPanel1.Widgets.Add(_buttonEnd);

			_panelMap = new ScrollViewer();
			_panelMap.Id = "_panelMap";
			StackPanel.SetProportionType(_panelMap, Myra.Graphics2D.UI.ProportionType.Fill);

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 8;
			verticalStackPanel1.Widgets.Add(horizontalStackPanel1);
			verticalStackPanel1.Widgets.Add(_panelMap);

			
			Widgets.Add(verticalStackPanel1);
		}

		
		public Button _buttonStart;
		public SpinButton _spinButtonStep;
		public Button _buttonEnd;
		public ScrollViewer _panelMap;
	}
}
