/* Generated by MyraPad at 5/7/2024 1:39:46 PM */
using Myra;
using Myra.Graphics2D;
using Myra.Graphics2D.TextureAtlases;
using Myra.Graphics2D.UI;
using Myra.Graphics2D.Brushes;
using Myra.Graphics2D.UI.Properties;
using FontStashSharp.RichText;
using AssetManagementBase;

#if STRIDE
using Stride.Core.Mathematics;
#elif PLATFORM_AGNOSTIC
using System.Drawing;
using System.Numerics;
using Color = FontStashSharp.FSColor;
#else
// MonoGame/FNA
using Microsoft.Xna.Framework;
using Microsoft.Xna.Framework.Graphics;
#endif

namespace MUDMapBuilder.Editor.UI
{
	partial class MainForm: Panel
	{
		private void BuildUI()
		{
			var label1 = new Label();
			label1.Text = "<<";

			_buttonStart = new Button();
			_buttonStart.Id = "_buttonStart";
			_buttonStart.Content = label1;

			_spinButtonStep = new SpinButton();
			_spinButtonStep.Integer = true;
			_spinButtonStep.Width = 50;
			_spinButtonStep.Id = "_spinButtonStep";

			var label2 = new Label();
			label2.Text = ">>";

			_buttonEnd = new Button();
			_buttonEnd.Id = "_buttonEnd";
			_buttonEnd.Content = label2;

			var horizontalStackPanel1 = new HorizontalStackPanel();
			horizontalStackPanel1.Spacing = 8;
			horizontalStackPanel1.Widgets.Add(_buttonStart);
			horizontalStackPanel1.Widgets.Add(_spinButtonStep);
			horizontalStackPanel1.Widgets.Add(_buttonEnd);

			var label3 = new Label();
			label3.Text = "<<";

			_buttonZeroCompact = new Button();
			_buttonZeroCompact.Id = "_buttonZeroCompact";
			_buttonZeroCompact.Content = label3;

			_spinButtonCompact = new SpinButton();
			_spinButtonCompact.Maximum = 1000;
			_spinButtonCompact.Minimum = 0;
			_spinButtonCompact.Integer = true;
			_spinButtonCompact.Width = 50;
			_spinButtonCompact.Id = "_spinButtonCompact";

			var label4 = new Label();
			label4.Text = ">>";

			_buttonMaximumCompact = new Button();
			_buttonMaximumCompact.Id = "_buttonMaximumCompact";
			_buttonMaximumCompact.Content = label4;

			var horizontalStackPanel2 = new HorizontalStackPanel();
			horizontalStackPanel2.Spacing = 8;
			horizontalStackPanel2.Widgets.Add(_buttonZeroCompact);
			horizontalStackPanel2.Widgets.Add(_spinButtonCompact);
			horizontalStackPanel2.Widgets.Add(_buttonMaximumCompact);

			_panelMap = new ScrollViewer();
			_panelMap.Id = "_panelMap";
			StackPanel.SetProportionType(_panelMap, Myra.Graphics2D.UI.ProportionType.Fill);

			var verticalStackPanel1 = new VerticalStackPanel();
			verticalStackPanel1.Spacing = 8;
			verticalStackPanel1.Widgets.Add(horizontalStackPanel1);
			verticalStackPanel1.Widgets.Add(horizontalStackPanel2);
			verticalStackPanel1.Widgets.Add(_panelMap);

			
			Widgets.Add(verticalStackPanel1);
		}

		
		public Button _buttonStart;
		public SpinButton _spinButtonStep;
		public Button _buttonEnd;
		public Button _buttonZeroCompact;
		public SpinButton _spinButtonCompact;
		public Button _buttonMaximumCompact;
		public ScrollViewer _panelMap;
	}
}
